version: "3"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres

  todo-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
    restart: on-failure
    container_name: todo-client
    environment:
      - API_URL=127.0.0.1:8080

  todo-server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    restart: on-failure
    container_name: todo-server
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
      - ./server:/app # Look at the server directory and copy everything into the app folder in the container
    depends_on:
      - postgres
    environment:
      - PORT=8080
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
